-- CreateEnum
CREATE TYPE "AuditAction" AS ENUM ('DOCUMENT_CREATED', 'DOCUMENT_VIEWED', 'DOCUMENT_UPDATED', 'DOCUMENT_DELETED', 'DOCUMENT_ARCHIVED', 'DOCUMENT_RESTORED', 'DOCUMENT_DOWNLOADED', 'DOCUMENT_SHARED', 'DOCUMENT_VERSION_CREATED', 'DOCUMENT_VERSION_RESTORED', 'FOLDER_CREATED', 'FOLDER_UPDATED', 'FOLDER_DELETED', 'FOLDER_MOVED', 'DEPARTMENT_CREATED', 'DEPARTMENT_UPDATED', 'DEPARTMENT_DELETED', 'WORKFLOW_SUBMITTED', 'WORKFLOW_REVIEWER_ASSIGNED', 'WORKFLOW_APPROVED', 'WORKFLOW_REJECTED', 'WORKFLOW_CANCELLED', 'USER_CREATED', 'USER_UPDATED', 'USER_DISABLED', 'USER_ACTIVATED', 'USER_ROLE_ASSIGNED', 'USER_ROLE_REMOVED', 'ROLE_CREATED', 'ROLE_UPDATED', 'ROLE_DELETED', 'PERMISSION_ASSIGNED_TO_ROLE', 'PERMISSION_REMOVED_FROM_ROLE', 'USER_LOGIN', 'USER_LOGOUT', 'METADATA_FIELD_CREATED', 'METADATA_FIELD_UPDATED', 'METADATA_FIELD_DELETED', 'DOCUMENT_METADATA_ADDED', 'DOCUMENT_METADATA_UPDATED', 'DOCUMENT_METADATA_REMOVED');

-- CreateTable
CREATE TABLE "AuditLog" (
    "id" SERIAL NOT NULL,
    "action" "AuditAction" NOT NULL,
    "resource" TEXT NOT NULL,
    "resourceId" INTEGER,
    "userId" INTEGER NOT NULL,
    "metadata" JSONB,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "AuditLog_userId_idx" ON "AuditLog"("userId");

-- CreateIndex
CREATE INDEX "AuditLog_action_idx" ON "AuditLog"("action");

-- CreateIndex
CREATE INDEX "AuditLog_resource_idx" ON "AuditLog"("resource");

-- CreateIndex
CREATE INDEX "AuditLog_resourceId_idx" ON "AuditLog"("resourceId");

-- CreateIndex
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");

-- AddForeignKey
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
