export const RESOURCES = {
  ROLE_PERMISSION: 'rolePermission',
  USER_ROLE: 'userRole',
  DOCUMENT: 'document',
  USER: 'user',
  ROLE: 'role',
  PERMISSION: 'permission',
  AUDITLOG: 'auditLog',
  REPORT: 'report',
  NOTIFICATION: 'notification',
  WORKFLOW: 'workflow',
  COMMENT: 'comment',
  METADATA_FIELD: 'metadataField',
  DOCUMENT_METADATA: 'documentMetadata',
  DOCUMENT_SHARE: 'documentShare',
  DEPARTMENT: 'department',
  FOLDER: 'folder',
} as const;

export const ACTIONS = {
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update',
  DELETE: 'delete',
  UPLOAD: 'upload',
  DOWNLOAD: 'download',
  ARCHIVE: 'archive',
  RESTORE: 'restore',
  APPROVE: 'approve',
  REJECT: 'reject',
  ASSIGN: 'assign',
  GENERATE: 'generate',
  ACTIVATE: 'activate',
  DISABLE: 'disable',
  REMOVE: 'remove',
  MOVE: 'move',
  SUBMIT: 'submit',
  CANCEL: 'cancel',
} as const;

export const SCOPES = {
  OWN: 'own',
  ALL: 'all',
  SHARED: 'shared',
  ASSIGNED: 'assigned',
  DEPARTMENT: 'department',
} as const;
